### PR TITLE
Final fix for strin-version-lessp

### LINKED ISSUE #78: string-version-lessp mismatch
@Ki11erRabbit I hit merge too quickly and found another few cases where the new implementation of `string-version-lessp` does not match Emacs

```lisp
(string-version-lessp "101a" "100b") ;; Emacs: nil, Rune: t
(string-version-lessp "10" "0100") ;; Emacs: t, Rune: nil
```

### PR DESCRIPTION
**Pull request by Ki11erRabbit**
I implemented the Emacs C file `filevercmp.c` to fix #78. It is done in a not very idiomatic Rust since the original made heavy use of boolean and integer mixing but it should work.

Feel free to suggest any changes. I am thinking of moving the documentation from the Emacs source code to here, just give me some more time for that.

### CODE REVIEW

**Comment by CeleritasCelery** [comment]
Found a mismatch:

```rust
(string-version-lessp "." ".")
```

**Comment by CeleritasCelery** [comment]
> Where would the best place be for it?

When in doubt I try to mirror the directory structure of Emacs.

**Comment by CeleritasCelery** [comment]
Found another one:

```lisp
(string-version-lessp ".." ".a")
```

**Comment by CeleritasCelery** [comment]
Overall I think this looks pretty good, even if it is not very idiomatic, it is still quite clear. The only thing I would suggest is to change `filevercmp` to return `std::cmp::Ordering` instead of using integers.

**Comment by Ki11erRabbit** [comment]
I fixed the case you brought up and now I just need to clean up the code since there are redundant checks and awkward nesting.

**Comment by Ki11erRabbit** [comment]
Also I will create a crate called lib since `filevercmp.c` exists in a directory and move 'filevercmp.rs` over to there.

**Comment by CeleritasCelery** [comment]
We don't need another crate, just a directory.

**Pull request merged**
