### PR TITLE
Create initial rune-core crate with only hashmap

### PR DESCRIPTION
**Pull request by Qkessler**
## Change Summary

This is the first step to refactor the core out of the main crate. The idea with this PR is to **just** include the changes on the crate structure itself, with a sample module moved to core. The idea with separating the PRs that I do
for this refactoring is to make the whole process easier to review + making sure there are no regressions on the refactors we do.

I started moving hashmap, which is typing that is used both in rune-core and the main crate, hence why moved to rune-core. I'll move other modules to rune-core little by little, as we get closer with PRs.

## Risks associated with this change
There isn't a risk, we are just refactoring and we can verify no regressions with CI.

## Testing
Ran CI on my master branch, with everything passing. I expect the CI as part of the PR to be passing as well.

### CODE REVIEW

**Comment by Qkessler** [comment]
This is the first crate for the rune-core refactor, discussed on this issue #47. As soon as this is merged, I'll publish other PRs with other modules being included.

The only module that won't be included for now is the separation of tagged.rs (don't have all the details) but we'll have to think whether the Symbol is a blocker to the core refactor, and we should think about a way to solve it cleanly.

**Comment by Qkessler** [comment]
P.S: We should consider removing Netlify deploys and previews on PRs, specially if we build the documentation website with our CI (because we need the build dependencies). Once that's removed, we can publish a CI step to build the preview ourselves, if that's something we want to support.

**Comment by Qkessler** [comment]
Once this is merged, I have ready the next PR on my `core-macros` branch: https://github.com/Qkessler/rune/tree/core-macros

**Comment by CeleritasCelery** [comment]
This looks good. 

> We should consider removing Netlify deploys and previews on PRs, specially if we build the documentation website with our CI (because we need the build dependencies)

I am not sure how to do that. Do we need to add a condition to the GitHub actions?

**Comment by Qkessler** [comment]
We need to configure the netlify site (probably on Site Configuration) to remove the PR previews. I'll find something more concrete and let you know.

**Comment by CeleritasCelery** [comment]
I found the setting and turned it off.

**Pull request merged**
